### ISSUE TITLE
after updating from 3.12.0 to 3.13.1 build time increase from 1m 14s to over 60m

### ISSUE THREAD

**Issue by StefanSchoof** [terser/terser#204]
**Bug report or Feature request?**
bug

**Version (complete output of `terser -V`)**
3.13.1
**Complete CLI command or `minify()` options used**
I use terser over webpack. My code is found at https://github.com/StefanSchoof/espresso/tree/terser/func
The code is small (two typescript files; 59 lines and 95 lines for test)
The Build at 3.12.0 works in 1m 14 https://dev.azure.com/sschoof/espresso/_build/results?buildId=341 (click at function job to see log)
The Build at 3.13.0 fails after 54s with a cannot read property start of undefined: https://dev.azure.com/sschoof/espresso/_build/results?buildId=342 (click at function job to see log) 
The Build at 3.13.1 got cancelled after 60 minutes. https://dev.azure.com/sschoof/espresso/_build/results?buildId=343 (there are other failing builds with 3.13.1: https://dev.azure.com/sschoof/espresso/_build/results?buildId=331, https://dev.azure.com/sschoof/espresso/_build/results?buildId=326)
The only difference between these are the terser version. (See https://github.com/StefanSchoof/espresso/commits/terser)

**`terser` input**

**`terser` output or error**

**Expected result**

**Comment by fabiosantoscode** [comment]
I'm going to investigate, but can you possibly remove code until we find the offender?

**Comment by StefanSchoof** [comment]
I am currently have only a smartphone with an ssh connection to a Linux with the code. This reduces my ways to inspect the issue. When I am back at my PC I will give it a try

**Comment by fabiosantoscode** [comment]
Coolsies :) I'll keep investigating, this bug is terrible.

**Comment by fabiosantoscode** [comment]
Can't reproduce on my machine :( will try in a VM

**Comment by StefanSchoof** [comment]
On a Standard DS2 v2 (2 vcpus, 7 GB memory) Azure VM I can reproduce. I reduced the causing code in https://github.com/StefanSchoof/espresso/blob/terser/func/src/switch/switch.ts a little bit.

**Comment by fabiosantoscode** [comment]
Ok, thanks for reducing the code. I was having trouble with typescript but used your own now.

**Comment by fabiosantoscode** [comment]
Do you also compile the test?

**Comment by fabiosantoscode** [comment]
Can you try to make this only go through terser? For example, compile the TS to another file and run terser on that file to see if it still freezes.

I was wrong about reproducing it before, I was just hitting #202 and thought I found the issue.

**Comment by StefanSchoof** [comment]
When I run
```
npx webpack
```
it takes forever.

When I run
```
npx webpack --mode development
npx terser dist/switch/switch.js
```
I get a result fast.

**Comment by StefanSchoof** [comment]
I removed the test file and the problem still occurs

**Comment by StefanSchoof** [comment]
I replaced the typescript with the js from the typescript compiler. Still occurs
https://github.com/StefanSchoof/espresso/blob/terser/func/src/switch/switch.js

**Comment by fabiosantoscode** [comment]
What's the command you're using @StefanSchoof ? I'm creating a new VM to try and reproduce. Make sure you pass '-mc' after the filename!

**Comment by fabiosantoscode** [comment]
I've created https://github.com/webpack-contrib/terser-webpack-plugin/issues/48. Can you fill in your details?

**Comment by StefanSchoof** [comment]
I did it. Thanks for your help, especially since the issue seams not be in terser.

**Comment by StefanSchoof** [comment]
I was able to create a pure terser repro (without webpack):
I added a [terser.js](https://github.com/StefanSchoof/espresso/blob/terser/func/terser.js) which tries to minify the [input.js](https://github.com/StefanSchoof/espresso/blob/terser/func/input.js). Running a 
```
node terser.js
```
seems to take forever.

**Comment by nifgraup** [comment]
Regression point 842392e59329dc05481dc21f0c5f74f3a2061b6d, bisected with terser.js & input.js as test case.

**Comment by fabiosantoscode** [comment]
Sorting through this mess. I'm still at 23325 lines. Next time I'm making you guys make the file smaller :P

**Comment by StefanSchoof** [comment]
I heard there is a tool named terser to reduce the file size ;)

**Comment by fabiosantoscode** [comment]
Hahahaha :)

**Comment by fabiosantoscode** [comment]
Binary search is a blessing though, this could take days otherwise.

**Comment by StefanSchoof** [comment]
Had you tried add some logging into https://github.com/terser-js/terser/commit/842392e59329dc05481dc21f0c5f74f3a2061b6d#diff-00fe37b20ddfb9ecc9c492b0725fa2b2R1232 to see which code part loops there at the end?

With no knowledge of the code, I think it tries to optimize the then part and then an other thing reverts this and so on.

**Comment by fabiosantoscode** [comment]
I've tried that, that's why I'm reducing the bundle. 105 lines...

**Comment by fabiosantoscode** [comment]
Temporarily reverted  842392e, will release a beta version so you can test it.

**Comment by fabiosantoscode** [comment]
Published 3.14.0-beta, can you try it @StefanSchoof ?

**Comment by Conduitry** [comment]
This beta doesn't seem to include the necessary `dist/bundle.js`. Can you mark the old version as `latest` again in npm? I was just bitten by this when updating dependencies.

**Comment by StefanSchoof** [comment]
My tests are somewhat inconclusive. Running the `terser.js` against the `input.js` succeed with the 3.14.0-beta, but my webpack build still does not succeed: https://dev.azure.com/sschoof/espresso/_build/results?buildId=372

Try to investigate further...

**Comment by StefanSchoof** [comment]
Okay, found the cause for this behavior. My project had an dependency to the beta version, but terser-webpack-plugin stayed at the 1.13.1 version. After I forced to use this it webpack works again in under one minute.

**Comment by fabiosantoscode** [comment]
Thanks for informing me @Conduitry I wasn't aware that beta versions became latest on release.

**Comment by fabiosantoscode** [comment]
It's settled then. `-b` dies and the commit stays reverted. This will take some work, so if someone would volunteer that would be great

**Comment by StefanSchoof** [comment]
@fabiosantoscode you can set an other tag then latest for an beta release, see https://docs.npmjs.com/cli/publish

**Comment by fabiosantoscode** [comment]
I already did!

**Comment by eltonio450** [comment]
Hello,

It seems we are facing an issue that looks like this one on CircleCI. I am not sure however which version is affected by the bug and which is not. And it seems related but not 100% sure...

The issue is either (1) a timeout (30 minutes, which occurs only in CircleCI) or (2) an error such as:
```
Error: EFAULT: bad address in system call argument, read
    at Object.readSync (fs.js:494:3)
    at tryReadSync (fs.js:333:20)
    at Object.readFileSync (fs.js:362:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:20)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/circleci/repo/node_modules/terser-webpack-plugin/dist/minify.js:8:38)
fs.js:115
    throw err;
```
Not sure that 1 and 2 are related however. Behaviour is not deterministic

Disabling terser-webpack-plugin (we use webpack) fixes both issues.

Our locked version is terser 3.14.

So:
1) Should we downgrade to 3.12 ? 
2) What can we do to narrow the bug ?

Thank you :)

**Comment by eltonio450** [comment]
ok, so:

the webpack-terser-plugin automatically enables parallelism and caching. Disabling both fixes the issue on CircleCI if it helps :). Not sure if it's considered as a bug of terser or circleCI

**Comment by dylansmith** [comment]
@eltonio450 were you seeing exit code > 0 for this `EFAULT` issue? I'm also seeing it, it's impacting our production system, and the build passes 😱

**Comment by dylansmith** [comment]
Also, should add that we see `ENOMEM` in CircleCI before the `EFAULT`:

```sh
Error: ENOMEM: not enough memory, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:361:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:20)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
fs.js:114
    throw err;
    ^

Error: EFAULT: bad address in system call argument, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:361:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:20)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by eltonio450** [comment]
i am not sure anymore, but the not enough memory seems to be some kind of timeout in our case. Did you try disabling parallelization and caching ?

**Comment by dylansmith** [comment]
Webpack was running 3 build configurations in parallel, each having a terser step. We tried reverting back to uglify and had similar issues, so this is probably not a terser issue specifically. We have switched to running the build configurations in series and this resolved the issue.

**Comment by fabiosantoscode** [comment]
Can this still be reproduced?

Reading this PR makes me believe this is a webpack thing (since they got around it by disabling parallelism): https://github.com/magda-io/magda/pull/2233

@evilebottnawi have you fixed this on your end?

**Comment by evilebottnawi** [comment]
Should be fixed, anyway speedup terser always is good, so if you can increase perf for terser, it will be awesome

**Comment by StefanSchoof** [comment]
I started a build of my old branch and still seems not to finish: https://dev.azure.com/sschoof/espresso/_build/results?buildId=1350&view=logs&j=dd0cdf81-99cc-5b13-4144-b5aff478827b

**Comment by StefanSchoof** [comment]
The https://github.com/StefanSchoof/espresso/blob/terser/func/terser.js and which can reproduce the problem without any webpack involved

**Comment by fabiosantoscode** [comment]
I downloaded your files using wget and ran the build just fine (both on the latest master and `4.1.0`). Maybe you just don't have enough RAM. That's a pretty big file. There's some discussion over at webpack-plugin-terser on making Terser only minify individual files instead of chunks, which can get really large.

**Comment by StefanSchoof** [comment]
Maybe I misunderstood you. The old problem is reproduceable with the old terser version (3.13). It was fixed by reverting https://github.com/terser/terser/commit/842392e59329dc05481dc21f0c5f74f3a2061b6d in 3.14: https://github.com/terser/terser/issues/204#issuecomment-450500663
Terser works since that without any issue. But I have no knowledge of the reverted change got back in again.

**Comment by fabiosantoscode** [comment]
Oh cool :) I thought it was back again, I didn't remember that got fixed with a revert and didn't read enough :) Thanks for letting me know anyway

**Comment by StefanSchoof** [comment]
Your are welcome. Thank you for terser.
